# fly.toml app configuration file generated for pokeglory-discord-bot on 2024-07-29T18:15:05+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pokeglory-discord-bot'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 3000
    protocol = "tcp"
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  swap_size_mb = 512
