import dotenv from "dotenv";

dotenv.config();

const {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  POKEGLORY_API_URL = "https://pokeglory.pl",
  POKEGLORY_DISCORD_BOT_SECRET,
  POKEGLORY_GAME_CHAT_CHANNEL_ID,
  POKEGLORY_GAME_CHAT_CHANNEL_NAME = "💬｜chat-w-grze",
  POKEGLORY_GAME_CHAT_SYNC_INTERVAL_MS = "5000",
} = process.env;

if (!DISCORD_TOKEN || !DISCORD_CLIENT_ID) {
  throw new Error("Missing environment variables");
}

export const config = {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  POKEGLORY_API_URL,
  POKEGLORY_DISCORD_BOT_SECRET,
  POKEGLORY_GAME_CHAT_CHANNEL_ID,
  POKEGLORY_GAME_CHAT_CHANNEL_NAME,
  POKEGLORY_GAME_CHAT_SYNC_INTERVAL_MS,
};
