import dotenv from "dotenv";

dotenv.config();

const {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  POKEGLORY_API_URL = "https://pokeglory.pl",
  POKEGLORY_DISCORD_BOT_SECRET,
  POKEGLORY_GAME_CHAT_CHANNEL_ID,
  POKEGLORY_GAME_CHAT_CHANNEL_NAME = "💬｜chat-w-grze",
  POKEGLORY_GAME_CHAT_SYNC_INTERVAL_MS = "5000",
  POKEGLORY_UPDATES_CHANNEL_ID,
  POKEGLORY_UPDATES_CHANNEL_NAME = "📢｜aktualizacje",
  POKEGLORY_UPDATES_SYNC_INTERVAL_MS = "5000",
  POKEGLORY_WELCOME_CHANNEL_ID,
  POKEGLORY_WELCOME_CHANNEL_NAME = "👋｜lobby",
  POKEGLORY_VERIFIED_ROLE_ID,
  POKEGLORY_VERIFIED_ROLE_NAME = "Zweryfikowany",
} = process.env;

if (!DISCORD_TOKEN || !DISCORD_CLIENT_ID) {
  throw new Error("Missing environment variables");
}

export const config = {
  DISCORD_TOKEN,
  DISCORD_CLIENT_ID,
  POKEGLORY_API_URL,
  POKEGLORY_DISCORD_BOT_SECRET,
  POKEGLORY_GAME_CHAT_CHANNEL_ID,
  POKEGLORY_GAME_CHAT_CHANNEL_NAME,
  POKEGLORY_GAME_CHAT_SYNC_INTERVAL_MS,
  POKEGLORY_UPDATES_CHANNEL_ID,
  POKEGLORY_UPDATES_CHANNEL_NAME,
  POKEGLORY_UPDATES_SYNC_INTERVAL_MS,
  POKEGLORY_WELCOME_CHANNEL_ID,
  POKEGLORY_WELCOME_CHANNEL_NAME,
  POKEGLORY_VERIFIED_ROLE_ID,
  POKEGLORY_VERIFIED_ROLE_NAME,
};
